# Generated by Django 5.1 on 2024-08-25 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_feedback_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedback1',
        ),
    ]
