# Generated by Django 5.1.1 on 2024-10-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
